### ISSUE TITLE
引入了quartz.net 去定时调用从容器中获取某个service后，原有逻辑报SmartSql.Alias:[SmartSql] already exist. 错误

### ISSUE THREAD

**Issue by kylix999** [dotnetcore/SmartSql#123]
## SmartSql version
 4.1.23

原来引入了一个AddRepositoryFromAssemblyFile方法，不直接引用repository的dll，而是扫描dll后动态注入 到容器中。
    一直用的没啥问题，然后后面发现引入quartz.net ，从另外一个线程去从容器里面resolve某个servcie之后，再去从前台通过controller去调用后台服务的service，在注入的时候，直接报
SmartSql.Alias:[SmartSql] already exist. 的错误。
 在如下的 AddRepositoryFromAssemblyFile 方法中的
 sqlMapper = sp.GetRequiredService<ISqlMapper>();这句话报错，
尝试将这个方法改成直接从我自定义的容器里面去获得
sqlMapper = KernelFacade.Current.Container.Resolve<ISqlMapper>(); 
逻辑这个自动注入的逻辑就可以正常运行了，
但是在AOP 使用 [Transcation]使用虚方法去处理事务的时候，仍然会报上面一样的错误，
AspectCore.DynamicProxy.AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> SmartSql.Alias:[SmartSql] already exist

strack Trace如下：
   at AspectCore.DynamicProxy.AspectActivator.Invoke[TResult](AspectActivatorContext activatorContext)
   at AspectCore.DynamicGenerated.ScheduleJobinfoService.AddScheduleJob(ScheduleJobinfoUIModel item)
   at Mes.Server.Schedule.Controller.ScheduleJobinfoController.AddScheduleJob(ScheduleJobinfoUIModel job) in E:\VSTS\HFMesFramework\20-Code\40-Application\04 Schedule\Mes.Server.Schedule.Controller\ScheduleJobinfoController.cs:line 52
而且这个地方没办法去改
请问下，这个是不是我对smartsql的哪里理解的不对，使用方式出现问题，才导致了这个报错的
是不是smartmapper这个对象不能在两个不同的线程里面同时使用同一个sqlmapper对象啊，我一遍创建了，另一边去处理就创建不了了？
 

AddRepositoryFromAssemblyFile 方法：
```
  public static SmartSqlDIBuilder AddRepositoryFromAssemblyFile(this SmartSqlDIBuilder builder, Action<AssemblyAutoRegisterOptions> setupOptions)
        {
            builder.AddRepositoryFactory();
            var options = new AssemblyAutoRegisterOptions
            {
                Filter = (type) => type.IsInterface
            };
            setupOptions(options);
            ScopeTemplateParser templateParser = new ScopeTemplateParser(options.ScopeTemplate);
            var assembly = Assembly.LoadFrom(options.AssemblyString);
            var allTypes = assembly.GetTypes().Where(options.Filter);
            foreach (var type in allTypes)
            {
                builder.Services.AddSingleton(type, sp =>
                {
                    ISqlMapper sqlMapper = null;

                    try
                    {
                      // sqlMapper = KernelFacade.Current.Container.Resolve<ISqlMapper>(); 
                       sqlMapper = sp.GetRequiredService<ISqlMapper>();
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.Message);
                    }
                    if (!String.IsNullOrEmpty(options.SmartSqlAlias))
                    {
                        sqlMapper = sp.EnsureSmartSql(options.SmartSqlAlias).SqlMapper;
                    }
                    var factory = sp.GetRequiredService<IRepositoryFactory>();
                    var scope = string.Empty;
                    if (!String.IsNullOrEmpty(options.ScopeTemplate))
                    {
                        scope = templateParser.Parse(type.Name);
                    }
                    return factory.CreateInstance(type, sqlMapper, scope);
                });
            }
            return builder;
        }
 
```

**Comment by kylix999** [comment]
是我自己的问题，我的servcieprovider构造了多个，导致不一致然后在smartsql里面解析的时候，认为是不同的容器，多次插入到  SmartSqlContainer.Instance中，现已经修复，和smartsql没关系，是我自己应用的问题
