### ISSUE TITLE
OpenConnection Unable to open connection to WriteDB

### ISSUE THREAD

**Issue by greggou** [dotnetcore/SmartSql#125]
## SmartSql version
4.1.28
## Database provider and version
ms sql 2014
## Steps to reproduce
程序运行一会就会出现这个错误

**Comment by Ahoo-Wang** [comment]
贴一下异常堆栈。

**Comment by greggou** [comment]
2019-12-25 17:06:44.389;ERROR 方法名：Fy.Starter.API.Filters.GlobalExceptionFilter 信息: api运行异常：   at SmartSql.DbSession.DefaultDbSession.Open() in C:\projects\smartsql\src\SmartSql\DbSession\DefaultDbSession.cs:line 80
   at SmartSql.Command.CommandExecuter.<>c__DisplayClass11_0.<ExecuteReader>b__0() in C:\projects\smartsql\src\SmartSql\Command\CommandExecuter.cs:line 137
   at SmartSql.Command.CommandExecuter.ExecuteWrap[TResult](Func`1 executeImpl, ExecutionContext executionContext, String operation) in C:\projects\smartsql\src\SmartSql\Command\CommandExecuter.cs:line 75
   at SmartSql.Command.CommandExecuter.ExecuteReader(ExecutionContext executionContext) in C:\projects\smartsql\src\SmartSql\Command\CommandExecuter.cs:line 134
   at SmartSql.Middlewares.CommandExecuterMiddleware.Invoke[TResult](ExecutionContext executionContext) in C:\projects\smartsql\src\SmartSql\Middlewares\CommandExecuterMiddleware.cs:line 48
   at SmartSql.Middlewares.TransactionMiddleware.Invoke[TResult](ExecutionContext executionContext) in C:\projects\smartsql\src\SmartSql\Middlewares\TransactionMiddleware.cs:line 22
   at SmartSql.Middlewares.AbstractMiddleware.Invoke[TResult](ExecutionContext executionContext) in C:\projects\smartsql\src\SmartSql\Middlewares\AbstractMiddleware.cs:line 23
   at SmartSql.DbSession.DefaultDbSession.Invoke[TResult](AbstractRequestContext requestContext) in C:\projects\smartsql\src\SmartSql\DbSession\DefaultDbSession.cs:line 301
   at SmartSql.DbSession.DefaultDbSession.QuerySingle[TResult](AbstractRequestContext requestContext) in C:\projects\smartsql\src\SmartSql\DbSession\DefaultDbSession.cs:line 393
   at SmartSql.SqlMapper.ExecuteImpl[TResult](Func`2 executeFunc) in C:\projects\smartsql\src\SmartSql\SqlMapper.cs:line 95
   at Fy.ProductManageService.EmployeeService.GetPageList(List`1 userIds, Int32 pageIndex, Int32 pageSize) in F:\WorkSpace\fengyun\project\01略阳电子商务\SVN\trunk\02SourceCode\AdminPortal\src\Fy.ProductManageService\EmployeeService.cs:line 108
   at Fy.Starter.API.Controllers.EmployeeController.GetEmployeePageList(EmployeeByPageReq model) in F:\WorkSpace\fengyun\project\01略阳电子商务\SVN\trunk\02SourceCode\AdminPortal\src\Fy.Starter.API\Controllers\EmployeeController.cs:line 289
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by greggou** [comment]
![image](https://user-images.githubusercontent.com/23184542/71447657-28a3dc00-276c-11ea-8add-c097ff425e79.png)

**Comment by greggou** [comment]
1.Message:
OpenConnection Unable to open connection to WriteDB.
2.InnerException：
message:Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
3.StackTrace:
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at SmartSql.DbSession.DefaultDbSession.Open() in C:\projects\smartsql\src\SmartSql\DbSession\DefaultDbSession.cs:line 73

**Comment by Ahoo-Wang** [comment]
连接池满了，建议检查慢查询以及连接池设置是否合理。

**Comment by greggou** [comment]
看到是连接池满了，默认的连接数是100，现在监测超过100就会报这个错误，是不是数据库连接的释放有问题呢？


greg
ghl_2312@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ahoo Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月26日(星期四) 上午9:14
收件人:&nbsp;"dotnetcore/SmartSql"<SmartSql@noreply.github.com&gt;;
抄送:&nbsp;"龙行天下"<313292384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnetcore/SmartSql] OpenConnection&nbsp;Unable&nbsp;to&nbsp;open&nbsp;connection&nbsp;to&nbsp;WriteDB (#125)




连接池满了，建议检查慢查询以及连接池设置是否合理。

**Comment by greggou** [comment]
1.使用动态仓储，观察控制台日志，执行查询结束不会执行dispose
2.使用SqlMapper或者dbSession，执行查询结束会执行dispose

动态仓储的使用是按照文档写的，还有其它注意事项吗？
